-- ########### RegisteredUser #################
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Chelsea','QLR97AEB8JF','mollis@ullamcorpernisl.co.uk',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Andrew','KRB65CIQ7ND','semper@justoeu.org',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Ethan','YIE05JUT0ZO','risus.Donec.egestas@Nuncsollicitudincommodo.com',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Timothy','EMA55AYI5NY','et.risus@lobortisquis.edu',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Darryl','BSB24QNW7SY','turpis.nec@luctusCurabituregestas.edu',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Callie','BIS87CQP4OT','tincidunt@in.net',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Blaze','VTH98FFI5PG','convallis@gravida.net',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Jasmine','GOB31BNF9ZA','conubia.nostra.per@ad.edu',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Xandra','LNR04CQV6CH','quis.accumsan.convallis@dictum.ca',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Wallace','QCS09ZEV1DQ','sed.sem@hymenaeosMaurisut.com',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Marny','MJY82PNX9DW','faucibus@consequatpurus.net',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Christopher','QDB21XNU9RA','consequat.lectus@nequeIn.org',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Marsden','UYI62LSP2ZX','rutrum@necluctus.edu',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Fitzgerald','IGV14VKZ7TG','euismod.est@massanonante.net',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Len','MFJ23MQW9TU','eu.augue@Morbimetus.edu',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Aurelia','SQK86DVN1SQ','velit.eget@odio.org',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Kirsten','MAX23ENO7LV','auctor.vitae@Donec.co.uk',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Nomlanga','VHF97NPW5TV','nibh@ipsumdolor.co.uk',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Kelly','MGR04WLG7BB','Etiam@semut.com',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Jason','PXB77WZD3LW','semper.rutrum.Fusce@facilisisfacilisis.ca',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Omar','NNY85GOV4KG','consectetuer.mauris.id@imperdieterat.ca',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Carl','DTL78YSJ2YS','Mauris.blandit@estarcu.com',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Lois','KFJ12VIJ0YU','egestas.blandit.Nam@Donec.edu',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Julian','SEK55HTW7LI','at.nisi@anteipsumprimis.net',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Pearl','VII41YPA6XO','massa.Integer@vitaediamProin.org',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Lyle','IQH88INM5PY','nibh@ametconsectetuer.com',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Barbara','UIK28GHQ6KH','porttitor@mollis.ca',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Danielle','RLJ02FTP7EM','amet@consequat.com',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Fredericka','UDS40DNF9ZN','consequat.lectus@nullaatsem.ca',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Arthur','QOU88FBO9NX','tincidunt@egetipsumDonec.org',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Penelope','XLT13NFT1PM','dignissim.pharetra@vitaedolor.org',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Griffin','CBN85QYZ4YM','Sed.eget@elitafeugiat.edu',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Norman','YOJ86NZN0FX','erat.semper.rutrum@sedconsequat.ca',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Rhiannon','ZKA03VWY1CK','amet.luctus.vulputate@mollis.edu',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Barbarian','EYZ70FES8IW','fringilla@orci.co.uk',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Julie','VZU87FZY7LL','sed.sapien@sagittis.org',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Wanda','JRI63MMQ7DH','mattis.ornare.lectus@acurnaUt.edu',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Martena','CKY44QTS7QR','ligula@Nuncsollicitudin.com',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Ocean','DTM99SNJ5MU','Nunc.mauris@sem.edu',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Vance','RGR11QQA8EE','porttitor.interdum@nonante.co.uk',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Tanek','AKG24UOB6KK','ut.sem.Nulla@ipsumdolor.com',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Bethany','VAX43EVK4KX','amet.risus@dui.net',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Raphael','NOL71KYV1QT','a@InloremDonec.co.uk',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Luke','EKQ04YUD2EV','eget.varius@musProin.com',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Zorita','XOY84DRH5RV','fermentum.metus@tellusNunclectus.org',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Harlan','ENA61DVK2QK','tincidunt@lectusquis.net',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Samuel','GSR86BWF3KY','in.dolor@pede.com',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Jamal','CAJ63PWQ3AM','dictum.placerat@Sedet.net',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Miranda','ZBR86YNL3NM','rutrum.Fusce.dolor@facilisis.edu',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Elvis','XNL14CVP5SU','non@laoreetlibero.org',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Ira','VRE61QFZ8WF','at@libero.co.uk',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Harrison','QZS10DXW8CZ','Donec.est@Phasellus.edu',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Lesley','KNH35KNX6PY','nec@NullafacilisiSed.co.uk',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Naida','GKR11QUN5WU','diam@ornareelitelit.co.uk',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Quintessa','KBB14OAN0GP','Vivamus@pulvinararcuet.com',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Mechelle','OUU99AOU9UB','In.mi@arcuVestibulum.edu',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Nina','UMF16ZWG2DI','varius@lectus.ca',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Anne','FTR03CDQ3CN','consequat@aaliquetvel.edu',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Benedict','JEP98AYT4EM','non@a.edu',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Madeline','IVJ17KJW2PR','convallis.erat@velconvallis.ca',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Rhonda','SXE48OJI4UW','molestie.orci.tincidunt@etnunc.com',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Destiny','TVO98FON5OZ','neque.tellus@primisin.com',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Mufutau','DUQ88LIU4CB','vitae@Naminterdum.org',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Audra','WVS30PBP6LK','orci@anteipsum.co.uk',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Cruz','QGO27FST3JR','sollicitudin.orci@semper.net',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Charles','ZRU03WNX5FJ','aliquet@laoreetlectusquis.org',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Ariana','MTQ99IEM4TN','nulla.Donec@nec.org',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Alvin','BVH39HEW6BJ','pellentesque@infaucibus.edu',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Nissim','YWE14DJR5NP','lobortis.tellus.justo@Nunc.net',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Mason','LOM13QCR6MQ','Praesent.eu@a.co.uk',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Holly','TMH01BTC3NV','Aenean.sed@magnaatortor.com',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Rogan','JEI25ETG7ZA','Etiam.vestibulum.massa@ametmassa.com',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Odette','DKG26GXD9UR','Quisque.varius.Nam@nequeseddictum.edu',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Amos','AYN05HNB1UV','justo@a.ca',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Zachery','WWB15MVY4AN','nibh.sit@sagittislobortis.co.uk',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Erich','JIP38PNH0EL','ac.metus.vitae@risusquis.ca',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Erasmus','CAB75HPN6KZ','dolor.Donec@interdumSed.co.uk',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Kyla','UIU66AVR9HV','massa.Mauris@aliquetlobortis.com',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Cadman','DLN21PST7IQ','ultrices.Vivamus@acfacilisisfacilisis.org',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Carolyn','GRC28BUG2JZ','ante.lectus.convallis@loremut.co.uk',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Amity','SRL36IGZ6DR','ornare.lectus@pretiumneque.co.uk',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Katell','LXJ62CUU5KT','et@Nunccommodoauctor.co.uk',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Bruce','TEE09UUD6AH','ornare.lectus@quisturpis.co.uk',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Addison','LPG64NOM7SW','senectus.et.netus@eumetusIn.net',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Maya','RDI98BBU1CN','accumsan.neque@euismodest.ca',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Ryan','BBS60EEZ8JI','arcu.eu.odio@aenimSuspendisse.edu',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Shaeleigh','LTR93NDP5NC','arcu.Vestibulum@fringillaDonec.net',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Cameron','KGA99PAH5AS','eu.erat.semper@quisdiamluctus.ca',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Kylan','JKP39YJF3HA','Integer.id@semvitae.net',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Brent','CSV20VQD0TY','et.netus.et@aliquetlibero.org',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Aline','PKK52TGI4UF','lorem@risus.org',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Ferris','YKM13RMW5XS','felis.Nulla.tempor@justo.net',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Colin','VDC60EFV8TY','semper.tellus@lobortis.edu',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Ian','XRY22YKU9VT','amet@nasceturridiculus.net',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Elton','MVT26FOP8EM','accumsan@variusorciin.net',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Josephine','IXO91JTN6SG','tincidunt@Etiamvestibulummassa.net',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Rachel','SXZ16JXZ3OB','rhoncus.Nullam.velit@leoelementumsem.co.uk',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Emerald','BBD90QHH0KF','lorem.vitae.odio@sapienimperdietornare.ca',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Vivian','LAG31CVQ1JR','nec@anteipsum.com',FALSE);
INSERT INTO RegisteredUser (username,password,email,isBanned) VALUES ('Kareem','BYY94PMH6YT','auctor.vitae.aliquet@netus.ca',FALSE);

-- ##################### Country ####################
INSERT INTO Country (name) VALUES ('Colombia');
INSERT INTO Country (name) VALUES ('Seychelles');
INSERT INTO Country (name) VALUES ('Mauritania');
INSERT INTO Country (name) VALUES ('Saint Pierre and Miquelon');
INSERT INTO Country (name) VALUES ('China');
INSERT INTO Country (name) VALUES ('United States Minor Outlying Islands');
INSERT INTO Country (name) VALUES ('Tunisia');
INSERT INTO Country (name) VALUES ('Cocos (Keeling) Islands');
INSERT INTO Country (name) VALUES ('Paraguay');
INSERT INTO Country (name) VALUES ('Algeria');
INSERT INTO Country (name) VALUES ('Guinea');
INSERT INTO Country (name) VALUES ('Singapore');
INSERT INTO Country (name) VALUES ('Honduras');
INSERT INTO Country (name) VALUES ('Bahrain');
INSERT INTO Country (name) VALUES ('Cook Islands');
INSERT INTO Country (name) VALUES ('Liberia');
INSERT INTO Country (name) VALUES ('Turkey');
INSERT INTO Country (name) VALUES ('Hungary');
INSERT INTO Country (name) VALUES ('Croatia');
INSERT INTO Country (name) VALUES ('Sierra Leone');
INSERT INTO Country (name) VALUES ('Trinidad and Tobago');
INSERT INTO Country (name) VALUES ('Saint Pierre and Miquelon');
INSERT INTO Country (name) VALUES ('Estonia');
INSERT INTO Country (name) VALUES ('Dominican Republic');
INSERT INTO Country (name) VALUES ('New Zealand');
INSERT INTO Country (name) VALUES ('Congo (Brazzaville)');
INSERT INTO Country (name) VALUES ('Saint Lucia');
INSERT INTO Country (name) VALUES ('Trinidad and Tobago');
INSERT INTO Country (name) VALUES ('Malawi');
INSERT INTO Country (name) VALUES ('Central African Republic');
INSERT INTO Country (name) VALUES ('French Guiana');
INSERT INTO Country (name) VALUES ('Puerto Rico');
INSERT INTO Country (name) VALUES ('Yemen');
INSERT INTO Country (name) VALUES ('Fiji');
INSERT INTO Country (name) VALUES ('Central African Republic');
INSERT INTO Country (name) VALUES ('Spain');
INSERT INTO Country (name) VALUES ('Niger');
INSERT INTO Country (name) VALUES ('Cuba');
INSERT INTO Country (name) VALUES ('Tuvalu');
INSERT INTO Country (name) VALUES ('Mayotte');
INSERT INTO Country (name) VALUES ('Samoa');
INSERT INTO Country (name) VALUES ('Malawi');
INSERT INTO Country (name) VALUES ('Bulgaria');
INSERT INTO Country (name) VALUES ('Christmas Island');
INSERT INTO Country (name) VALUES ('Kazakhstan');
INSERT INTO Country (name) VALUES ('Israel');
INSERT INTO Country (name) VALUES ('Bangladesh');
INSERT INTO Country (name) VALUES ('Dominica');
INSERT INTO Country (name) VALUES ('Serbia');
INSERT INTO Country (name) VALUES ('Sweden');
INSERT INTO Country (name) VALUES ('Mauritania');
INSERT INTO Country (name) VALUES ('Sweden');
INSERT INTO Country (name) VALUES ('Norfolk Island');
INSERT INTO Country (name) VALUES ('Bonaire, Sint Eustatius and Saba');
INSERT INTO Country (name) VALUES ('Belarus');
INSERT INTO Country (name) VALUES ('United Arab Emirates');
INSERT INTO Country (name) VALUES ('Dominican Republic');
INSERT INTO Country (name) VALUES ('Jersey');
INSERT INTO Country (name) VALUES ('Togo');
INSERT INTO Country (name) VALUES ('Bahrain');
INSERT INTO Country (name) VALUES ('Nepal');
INSERT INTO Country (name) VALUES ('Ghana');
INSERT INTO Country (name) VALUES ('Australia');
INSERT INTO Country (name) VALUES ('Fiji');
INSERT INTO Country (name) VALUES ('Syria');
INSERT INTO Country (name) VALUES ('Japan');
INSERT INTO Country (name) VALUES ('Laos');
INSERT INTO Country (name) VALUES ('Azerbaijan');
INSERT INTO Country (name) VALUES ('Bahrain');
INSERT INTO Country (name) VALUES ('French Guiana');
INSERT INTO Country (name) VALUES ('Germany');
INSERT INTO Country (name) VALUES ('Saint Martin');
INSERT INTO Country (name) VALUES ('Yemen');
INSERT INTO Country (name) VALUES ('Korea, North');
INSERT INTO Country (name) VALUES ('Saint Pierre and Miquelon');
INSERT INTO Country (name) VALUES ('Nigeria');
INSERT INTO Country (name) VALUES ('Algeria');
INSERT INTO Country (name) VALUES ('Grenada');
INSERT INTO Country (name) VALUES ('Turkmenistan');
INSERT INTO Country (name) VALUES ('Reunion');
INSERT INTO Country (name) VALUES ('British Indian Ocean Territory');
INSERT INTO Country (name) VALUES ('Heard Island and Mcdonald Islands');
INSERT INTO Country (name) VALUES ('Tokelau');
INSERT INTO Country (name) VALUES ('Uganda');
INSERT INTO Country (name) VALUES ('Liechtenstein');
INSERT INTO Country (name) VALUES ('Egypt');
INSERT INTO Country (name) VALUES ('Luxembourg');
INSERT INTO Country (name) VALUES ('El Salvador');
INSERT INTO Country (name) VALUES ('Nicaragua');
INSERT INTO Country (name) VALUES ('Niue');
INSERT INTO Country (name) VALUES ('Cayman Islands');
INSERT INTO Country (name) VALUES ('New Caledonia');
INSERT INTO Country (name) VALUES ('Chile');
INSERT INTO Country (name) VALUES ('Korea, South');
INSERT INTO Country (name) VALUES ('Kazakhstan');
INSERT INTO Country (name) VALUES ('Jamaica');
INSERT INTO Country (name) VALUES ('Iraq');
INSERT INTO Country (name) VALUES ('Sint Maarten');
INSERT INTO Country (name) VALUES ('Andorra');
INSERT INTO Country (name) VALUES ('Kiribati');

-- ################### CreditCard ##################
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Emma Gillespie','5041253650431245','2014-01-02T20:02:09-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Sawyer Fletcher','6355194127376399','2013-08-04T03:56:23-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Aphrodite Richmond','6574075500175935','2014-06-18T18:03:52-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Stone Mosley','0599842513216293','2014-01-31T16:27:03-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Oscar Chan','0195288060418791','2013-08-08T13:15:32-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Wayne Booth','0693458843715105','2014-10-03T19:52:06-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Orli Nelson','7795053162478302','2015-01-19T15:12:46-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Jolene Durham','8363434914739623','2014-06-10T12:23:46-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Priscilla Wynn','9459232709033290','2013-09-22T15:58:59-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Cheryl Mcdaniel','0319659098103236','2014-10-11T14:52:22-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Oleg Frost','8025168157542019','2013-07-18T19:59:35-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Ava Anthony','1443350608941052','2013-07-18T04:23:02-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Desirae Andrews','7333955199090786','2014-11-06T03:29:27-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('ElliottWashington','8133013501902841','2013-10-09T19:16:06-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Fallon Bright','9230570851178736','2014-04-25T21:08:43-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Amaya Frederick','2951261395178984','2014-05-02T08:03:50-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('September Franklin','8937258927161708','2014-10-24T03:16:55-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Karen Douglas','5591003430819183','2014-08-27T20:08:11-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Carson Pate','2477190470670315','2014-04-17T17:06:00-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Odysseus Horne','0374934046833693','2014-02-24T10:52:06-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Kiara Pruitt','1229743277327977','2014-01-20T17:30:10-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Myra King','6300302217939952','2014-05-10T15:42:39-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Cairo Blackwell','4792422381298298','2013-05-07T20:51:02-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Fallon Byers','2323830326692775','2014-10-19T17:23:29-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Zoe Valdez','6274436352199378','2014-09-01T00:51:51-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Kyla Hyde','9050396560402283','2014-01-08T03:07:54-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Charity Jones','0825434130273299','2015-03-15T14:37:11-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Brendan Carver','6580504089937086','2013-12-18T10:41:09-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Chava Diaz','1318354470902574','2014-02-11T08:29:23-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Blossom Barr','2777665851630381','2015-03-14T16:15:37-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Demetria Langley','2145710822774978','2013-10-09T03:34:26-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Elliott Lancaster','6101678498687852','2013-08-24T05:39:24-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Henry Hull','4770739009523930','2013-06-02T04:30:21-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Lacota Wallace','5130672609162480','2013-11-12T01:41:40-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Scarlett Gaines','6792128594579474','2013-09-15T01:13:22-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Driscoll Kane','1703984658208148','2013-08-27T05:14:04-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Darius Romero','5198380384338320','2014-07-25T11:20:51-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Nathan Lyons','0540344384713458','2015-02-25T10:52:02-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Holly Adams','8198368942091469','2014-10-02T14:59:01-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Hu Cox','6240813814592625','2014-09-02T20:25:04-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Tatyana Cantu','5998540114035627','2014-01-29T14:04:31-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Desiree Guerra','1277567843065121','2015-03-15T05:04:04-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Aquila Mcclure','0283542974185109','2014-11-08T23:30:23-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Tate Compton','5699245103457236','2014-11-09T13:40:36-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Griffith Carpenter','9863867341160405','2013-06-14T05:29:01-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Ila Montoya','8028331871305488','2014-05-12T00:20:07-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Latifah Petersen','1898418083834140','2015-01-02T10:48:02-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Abbot Mullins','4481956723255876','2015-02-19T08:08:32-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Molly Atkins','2397999791045792','2013-08-31T22:31:25-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Palmer Hancock','8191813344459324','2013-10-11T08:32:22-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Tyler Boyer','5814082267474537','2014-07-12T12:42:55-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Driscoll Paul','9831172764706886','2013-06-22T08:29:53-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Herman Sampson','0254541690958984','2014-05-23T15:19:33-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Willa Cunningham','8033279736430376','2014-11-26T03:20:46-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Carla Mendoza','3504148613056276','2014-09-24T01:50:10-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Emma Dorsey','5323249678120827','2015-03-25T09:01:37-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Flavia Craig','1111900092737068','2015-02-25T14:56:28-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Freya Hicks','7971787924685599','2013-05-13T23:24:32-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Christian Weber','9506178591802974','2013-06-02T10:22:08-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Kato Coffey','3112098371547905','2013-08-09T01:39:51-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Harrison Pittman','3892067988532523','2015-01-27T16:47:26-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Chaney Gould','1351009221980745','2014-12-28T04:17:55-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Libby Lott','7117836466757483','2015-02-18T02:39:41-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Clinton Lamb','2854874449612143','2014-01-28T09:29:17-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Cora Faulkner','9704993129442683','2014-09-19T01:25:12-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Keith Chen','9422642390510436','2013-12-31T02:11:58-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Colette Ratliff','9435716103104219','2014-07-06T06:56:55-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Graham Hood','7382220185111785','2014-03-15T00:21:43-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Gabriel Dodson','1612871825063995','2014-01-17T22:29:11-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Farrah House','5789737192426859','2014-12-14T19:47:55-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Fay Olson','5680875117369158','2013-12-10T02:37:28-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Daquan Mann','4104186904039504','2014-12-24T03:21:13-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Dorian Cortez','2390364461699559','2014-03-10T05:35:00-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Silas Vasquez','1462555751597750','2014-06-22T07:30:32-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Keefe Moody','3404819938758744','2014-06-25T19:24:22-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Maggie Shepard','2807140052191124','2014-02-25T16:18:07-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Riley Thompson','5517247803614439','2015-01-09T12:43:02-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Vanna Harrington','5967090995280048','2014-02-05T08:47:00-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Lois Serrano','4201062236822218','2013-10-13T15:08:01-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Kamal Johnston','0070822824831871','2013-08-28T23:00:38-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Eden Cochran','8067784101248914','2014-09-20T04:14:10-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Yeo Guerra','2464478415670713','2014-06-16T15:38:13-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Ivory Barker','2434084556495626','2014-11-30T17:49:21-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Olivia Adkins','1026202743973042','2014-07-05T13:59:07-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Steven Adams','0109769518429667','2013-09-22T18:43:14-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Rose Pace','1058025896427081','2015-01-12T18:15:06-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Lesley Oliver','3293626845873506','2013-08-17T07:42:34-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Ora Mcclain','8153173684544763','2014-01-28T05:08:11-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Kelsie Best','0909804726066795','2013-10-29T23:15:33-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Danielle Anderson','0535281451535850','2013-09-15T05:36:36-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Ciara Delgado','6831925903286326','2013-12-12T20:23:57-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Aiko Chapman','7281940435201225','2014-11-21T04:58:23-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Amanda Mejia','7359761319841937','2015-01-15T21:41:48-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Dean Harris','9833361305632887','2014-08-08T03:30:30-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Elton Rush','7282909551997543','2014-05-09T23:20:20-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Lucas Spencer','8364361131158080','2014-12-12T07:37:15-08:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Emerald Short','7049780699216193','2013-07-08T01:07:53-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Jasmine Nash','0387407769290271','2014-10-16T13:18:05-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Camilla Mccray','8420122773735318','2013-06-13T19:36:43-07:00');
INSERT INTO CreditCard (ownerName,number,dueDate) VALUES ('Lara Wells','3871451410233790','2014-07-25T06:49:24-07:00');

-- ############### Address ######################
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('P.O. Box 130, 3920 Cras Ave','0209VV','Poggio San Marcello',71);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('P.O. Box 148, 5028 Ante Rd.','4948','Gouda',3);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('733-2795 Diam Ave','61202','Siena',69);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('806-8948 Interdum Ave','96037','Moen',38);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('166-4891 Risus Street','9714','Casoli',82);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('4894 Et Road','408615','Carleton',80);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('583-292 Ornare Street','N2N 0M8','Villers-la-Bonne-Eau',37);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('P.O. Box 418, 967 Ornare, St.','34095','Gudivada',13);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('360 Suspendisse St.','71913','Barcelona',57);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('7877 Cum Av.','G8B 4Y5','Sainte-Flavie',7);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('270-3815 Proin Road','X8S 7A4','Osasco',49);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #545-6216 Sollicitudin Street','5173','Pointe-au-Pic',65);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('119-7786 Lorem Rd.','1882','Bogaarden',31);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #312-7930 Aenean Av.','J0K 6W1','Westmount',9);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('P.O. Box 497, 405 Sapien. Avenue','3493VU','Albisola Superiore',65);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #150-1576 Luctus, Rd.','27904','Warren',14);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #801-1460 Augue Av.','3616','Todi',94);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('P.O. Box 454, 439 Orci. Rd.','27498','Wattrelos',3);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #633-9804 Nibh. Street','8380','Stockport',12);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #807-2616 Penatibus Av.','67450','Martello/Martell',55);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #706-9239 Eros Street','69655','Baltasound',81);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('787-166 Non St.','4082','Bowden',65);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('P.O. Box 605, 7560 Ut Av.','18124','San Piero a Sieve',48);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('8194 Sed Avenue','3582','Newport',53);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('874-7389 Sagittis. St.','11855','Queenstown',96);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #729-6209 Euismod Road','R5E 7T4','Roubaix',51);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('7423 Purus, St.','7217','Chesapeake',51);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #737-7240 Consectetuer Street','61740','Douai',58);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #909-7944 Dignissim St.','71305','Jacksonville',25);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('644-2187 Risus Av.','96008','Udaipur',52);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('9804 Cras St.','88309','Baili�vre',29);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #150-1887 Vestibulum, Rd.','26775','Cuddapah',47);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #341-8279 Ut, Street','6587','Donosti',63);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('226-4228 Vivamus Street','32867-189','Bhagalpur',77);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('P.O. Box 777, 5054 Et St.','C0 3QA','Drachten',43);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('9980 Commodo Ave','76109','Collinas',55);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('166-8836 Dictum Street','11800','Ferrere',84);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('6644 Egestas. Av.','6862WG','Durham',22);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #973-4459 Fusce Road','20723','Harlingen',29);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('8668 Turpis. Rd.','0057','Maltignano',78);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('7388 Leo Road','21890','Ransart',73);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('988-409 Urna St.','27463','Ingolstadt',2);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('765-1163 Ultricies Rd.','57399','Rochester',38);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #871-2331 Tristique Av.','2714','Bolsward',48);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #945-9728 Tempor Ave','8262','Whangarei',24);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('5708 Curabitur Rd.','07452','Welland',67);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('347-7890 Egestas, Street','9617','Torino',38);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('P.O. Box 620, 1954 Erat, Rd.','J2 3XU','Rocky Mountain House',44);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('989-1570 A, Rd.','05397','Bogaarden',81);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #106-5137 Eu Avenue','8888','Vilna',70);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('338-9053 Turpis. Avenue','276339','Dorval',76);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('2321 Et Rd.','5347','Bear',58);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #235-7271 Dignissim Rd.','59727','Huntsville',37);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #994-7415 Torquent Rd.','710029','Southaven',96);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #276-8519 Hendrerit Av.','55725','Saint-Dizier',38);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('3084 Pede. Rd.','5553','San Cristóbal de la Laguna',81);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('635-4360 Ante. Street','954770','Thorembais-les-B�guines',24);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('P.O. Box 242, 1723 Maecenas Street','52219','Marcinelle',23);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('559-1119 Urna Rd.','06813','Lauder',80);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('3955 Sagittis St.','94139-592','Wabamun',27);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #458-4004 Urna. Av.','X6C 3NY','Muzaffarpur',12);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #680-1174 Sagittis St.','20714','St. Thomas',27);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('450-9926 Mi Ave','6917','Millesimo',28);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('2315 Nec, Av.','1669','Hamme',17);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('506-4919 Purus Av.','2012','Sant''Agapito',97);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('P.O. Box 292, 4281 Orci St.','R8C 5B9','Malgesso',87);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('5010 Non, St.','3820','Autelbas',66);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('P.O. Box 951, 1776 Tellus St.','6862','Sherbrooke',58);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('217-1821 Eu, Ave','7536','Kanpur',73);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('P.O. Box 373, 6161 Elit Rd.','851954','Arsoli',98);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('191-2092 Non St.','1430AB','Neuville',63);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #765-9420 Arcu Avenue','09166-119','Llandovery',63);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #265-450 Eu, St.','70139','Roosendaal',24);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('1244 Vitae St.','7955LC','Aylesbury',90);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('446-199 At, Rd.','C9H 8X4','Hay River',73);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('833-4137 Nonummy Rd.','862294','Louth',50);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('6580 Ante. Street','71815','Scala Coeli',28);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #753-5494 Phasellus Road','82395','Villanova d''Albenga',86);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('921-2882 Tristique Road','51609','Brest',95);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #857-9187 Lectus Rd.','160649','Provost',85);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('P.O. Box 222, 6495 Aliquet Ave','3807','Port Moody',69);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('P.O. Box 910, 816 Tortor Rd.','126601','Guarapuava',16);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('P.O. Box 639, 2441 Ornare Street','62709','Arzano',95);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('4357 Sagittis. Rd.','51519','Preore',73);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('2413 Risus Street','07572','Sloten',35);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('P.O. Box 830, 8586 Tincidunt Street','68699','Clackmannan',40);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('P.O. Box 371, 9024 Diam Street','4114','Castel San Niccolò',11);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #674-7466 Nunc Road','64846','Kapolei',43);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('P.O. Box 556, 2620 Posuere St.','8754','Silvassa',14);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('P.O. Box 821, 3843 Pretium Street','54475-713','Baie-Saint-Paul',97);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('P.O. Box 350, 6930 Risus, Av.','3918','Queenstown',40);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('P.O. Box 904, 542 Mauris Road','J5Y 8P0','New Bombay',80);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #254-4690 A St.','9561','Gonnosnò',33);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('990-9248 Tincidunt Avenue','14919','Cuddalore',33);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #228-7930 Aliquet, St.','0177','Zeitz',52);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('2977 Lectus, St.','4332PE','St. Neots',48);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('295-562 Aliquam Road','43821','Bolano',64);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('P.O. Box 714, 8142 Magnis Street','25750','Villata',76);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('9340 Orci Avenue','6297','Gandhinagar',23);
INSERT INTO Address (addressLine,postalCode,city,idCountry) VALUES ('Ap #790-2133 Tempus Av.','K5A 7X6','Meeuwen-Gruitrode',78);

-- ###################### Product #########################
INSERT INTO Product (name,description,approved) VALUES ('et, rutrum eu, ultrices','turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('leo. Morbi neque tellus, imperdiet','Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('aliquam','dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('amet,','Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('diam','nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('mus. Donec dignissim magna a','enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('arcu. Sed eu','lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('aliquam iaculis, lacus pede sagittis','hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('ridiculus mus.','vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('Nunc','egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor.',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('Nunc ut','ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu.',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('mi eleifend egestas. Sed','massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('Mauris','consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('egestas. Aliquam nec enim. Nunc','pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio,',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('Nullam vitae diam. Proin dolor.','ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('lectus convallis est, vitae sodales','Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla.',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('laoreet lectus quis massa. Mauris','Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('In nec orci.','elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('iaculis odio. Nam interdum','lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('fringilla','malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('neque. Nullam nisl. Maecenas malesuada','Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('lacus.','aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('libero. Integer in magna. Phasellus','aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('mi lorem, vehicula et, rutrum','posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('sit amet, consectetuer adipiscing elit.','sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('scelerisque neque. Nullam nisl.','urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat.',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('Vivamus molestie dapibus','risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('nunc. In at pede.','est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('purus.','diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('vel sapien imperdiet ornare. In','commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in,',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('augue porttitor interdum. Sed','Vivamus non lorem vitae odio sagittis semper. Nam tempor diam',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('nunc id enim. Curabitur massa.','sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus.',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('nulla.','magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('ridiculus mus. Donec','Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('magna a tortor.','ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('et netus et','eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('mi. Aliquam gravida mauris','convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('nonummy.','cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat.',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('sapien','vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('accumsan convallis, ante lectus','ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum.',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('Curabitur','dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien.',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('Aliquam fringilla cursus purus.','natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus.',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('pellentesque. Sed dictum. Proin eget','ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('amet ultricies sem magna','Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('porttitor','lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('aptent taciti sociosqu ad','Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('et malesuada fames ac','nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet posuere, enim nisl elementum purus,',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('odio. Etiam ligula','nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis.',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('auctor velit. Aliquam','feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel,',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('commodo tincidunt nibh. Phasellus nulla.','ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam.',TRUE);
INSERT INTO Product (name,description,approved) VALUES ('consectetuer, cursus et, magna.','vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('diam. Proin dolor. Nulla','Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('accumsan interdum libero dui nec','et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et,',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('varius','Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('nisl sem, consequat nec,','Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('aliquet, metus urna','porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('non, vestibulum nec, euismod in,','montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('ipsum leo','quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('Cum','mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('Ut tincidunt orci','elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum,',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('Nunc lectus','Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('In ornare sagittis','consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus.',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('ac mi eleifend egestas. Sed','ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('enim, sit amet','molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('at, velit.','Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat.',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('Phasellus elit pede,','taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('venenatis vel, faucibus id,','ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('Donec','risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('lacus. Etiam','tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla,',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('ac risus. Morbi metus. Vivamus','parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit.',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('sit amet, faucibus ut, nulla.','scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('dis parturient montes,','pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('pharetra sed, hendrerit a, arcu.','dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero.',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('neque','sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('In nec orci. Donec nibh.','eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('Vestibulum ante','ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('augue.','Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('congue, elit','aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo.',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('consequat dolor vitae dolor. Donec','Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum,',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('fringilla','magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('est arcu ac orci.','ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('facilisis vitae, orci. Phasellus','hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('non','ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis,',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('magna. Praesent','Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('mauris id','elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('erat','Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('Cras eu tellus eu augue','dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('feugiat metus','nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('vel arcu.','nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('Nam nulla magna, malesuada','Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('Aenean sed pede nec','Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam.',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('lectus','sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('enim. Suspendisse aliquet, sem','lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('sem molestie sodales.','lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci,',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('ut eros','ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero.',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('eu','justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim,',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('sodales purus, in molestie','gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('Nam nulla magna,','risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede.',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('sit','mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper',FALSE);
INSERT INTO Product (name,description,approved) VALUES ('natoque penatibus et','libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem',FALSE);

-- ################## Buyer ###############
INSERT INTO Buyer (idUser) VALUES (1);
INSERT INTO Buyer (idUser) VALUES (2);
INSERT INTO Buyer (idUser) VALUES (3);
INSERT INTO Buyer (idUser) VALUES (4);
INSERT INTO Buyer (idUser) VALUES (5);
INSERT INTO Buyer (idUser) VALUES (6);
INSERT INTO Buyer (idUser) VALUES (7);
INSERT INTO Buyer (idUser) VALUES (8);
INSERT INTO Buyer (idUser) VALUES (9);
INSERT INTO Buyer (idUser) VALUES (10);
INSERT INTO Buyer (idUser) VALUES (11);
INSERT INTO Buyer (idUser) VALUES (12);
INSERT INTO Buyer (idUser) VALUES (13);
INSERT INTO Buyer (idUser) VALUES (14);
INSERT INTO Buyer (idUser) VALUES (15);
INSERT INTO Buyer (idUser) VALUES (16);
INSERT INTO Buyer (idUser) VALUES (17);
INSERT INTO Buyer (idUser) VALUES (18);
INSERT INTO Buyer (idUser) VALUES (19);
INSERT INTO Buyer (idUser) VALUES (20);
INSERT INTO Buyer (idUser) VALUES (21);
INSERT INTO Buyer (idUser) VALUES (22);
INSERT INTO Buyer (idUser) VALUES (23);
INSERT INTO Buyer (idUser) VALUES (24);
INSERT INTO Buyer (idUser) VALUES (25);
INSERT INTO Buyer (idUser) VALUES (26);
INSERT INTO Buyer (idUser) VALUES (27);
INSERT INTO Buyer (idUser) VALUES (28);
INSERT INTO Buyer (idUser) VALUES (29);
INSERT INTO Buyer (idUser) VALUES (30);
INSERT INTO Buyer (idUser) VALUES (31);
INSERT INTO Buyer (idUser) VALUES (32);
INSERT INTO Buyer (idUser) VALUES (33);
INSERT INTO Buyer (idUser) VALUES (34);
INSERT INTO Buyer (idUser) VALUES (35);
INSERT INTO Buyer (idUser) VALUES (36);
INSERT INTO Buyer (idUser) VALUES (37);
INSERT INTO Buyer (idUser) VALUES (38);
INSERT INTO Buyer (idUser) VALUES (39);
INSERT INTO Buyer (idUser) VALUES (40);
INSERT INTO Buyer (idUser) VALUES (41);
INSERT INTO Buyer (idUser) VALUES (42);
INSERT INTO Buyer (idUser) VALUES (43);
INSERT INTO Buyer (idUser) VALUES (44);
INSERT INTO Buyer (idUser) VALUES (45);
INSERT INTO Buyer (idUser) VALUES (46);
INSERT INTO Buyer (idUser) VALUES (47);
INSERT INTO Buyer (idUser) VALUES (48);
INSERT INTO Buyer (idUser) VALUES (49);
INSERT INTO Buyer (idUser) VALUES (50);

-- ###################### Seller #########################
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (51,2,'Tempus Risus Donec PC','1-844-458-6944','porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et,',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (52,3,'Ipsum Associates','1-356-327-8589','nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (53,4,'Bibendum Fermentum Metus Corp.','327-2397','id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (54,5,'Eu Incorporated','1-382-984-1347','sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna.',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (55,6,'Vitae Velit Egestas Inc.','1-511-582-5303','turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (56,7,'Aliquet Molestie Tellus Institute','286-5356','non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (57,8,'Accumsan Convallis Industries','1-129-360-0902','gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (58,9,'Ullamcorper Duis Associates','1-913-310-3975','diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (59,10,'Eu Augue Inc.','1-322-906-3886','consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis.',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (60,11,'Suspendisse LLC','1-683-465-4340','tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus.',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (61,12,'Semper Egestas Urna Corporation','909-3441','mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (62,13,'Purus Accumsan Incorporated','915-6579','Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (63,14,'Eu Neque Pellentesque Consulting','654-3509','Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (64,15,'Ullamcorper Duis Cursus Foundation','596-5960','velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (65,16,'Dui LLP','1-335-593-4484','luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (66,17,'Libero Integer Industries','966-0419','adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum,',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (67,18,'Interdum Inc.','778-0848','gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (68,19,'Volutpat Ornare Facilisis Corp.','1-451-868-5551','quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (69,20,'Id Foundation','1-795-633-5451','Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (70,21,'Eu Euismod Ac Limited','441-8634','nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (71,22,'Proin Ultrices Corp.','193-8501','velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus,',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (72,23,'Lobortis Ultrices LLP','1-864-568-1401','In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (73,24,'Pharetra Quisque Incorporated','597-8689','Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (74,25,'In Sodales Elit Institute','1-608-528-4532','tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (75,26,'Arcu Incorporated','461-8708','pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui,',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (76,27,'Sollicitudin LLC','1-738-899-2868','lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (77,28,'Dui Associates','1-962-940-5748','Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum.',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (78,29,'Tellus Non Corporation','519-7715','cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate,',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (79,30,'Dui Limited','698-2943','nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (80,31,'At Augue Id Institute','784-4109','et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (81,32,'Mauris Vel Corp.','508-2787','Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui.',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (82,33,'Egestas LLP','626-7221','eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est,',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (83,34,'Aliquet Ltd','1-876-671-1526','facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (84,35,'Ut Eros Non Incorporated','1-603-502-4890','arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna.',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (85,36,'Ipsum Primis In Institute','1-297-843-5415','sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (86,37,'Sed Associates','1-540-434-7306','Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (87,38,'Sapien Molestie Orci LLC','168-7442','fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien.',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (88,39,'Gravida Sagittis Duis PC','1-274-544-1269','eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (89,40,'Placerat Augue Sed Ltd','1-318-537-3003','et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat,',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (90,41,'Etiam Ltd','804-6152','Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu,',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (91,42,'Sapien Cras Associates','645-3863','aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper.',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (92,43,'Phasellus Incorporated','1-768-522-9389','dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus.',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (93,44,'Laoreet Industries','428-4425','pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (94,45,'Odio Sagittis Corporation','570-4538','mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et,',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (95,46,'Sem Industries','1-377-729-2867','urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (96,47,'Sed Sapien Nunc Associates','1-727-249-2626','gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (97,48,'Eu Foundation','1-869-636-8643','et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero.',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (98,49,'Magnis Dis Incorporated','938-4997','dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (99,50,'Ullamcorper Eu LLP','1-167-499-5441','odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu.',TRUE);
INSERT INTO Seller (idUser,idAddress,companyName,cellPhone,description,isVisibleToAPI) VALUES (100,1,'Quisque Varius Limited','143-1078','sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus',FALSE);

-- ############# Administrator ######################
INSERT INTO Administrator (idUser) VALUES (1);
INSERT INTO Administrator (idUser) VALUES (2);
INSERT INTO Administrator (idUser) VALUES (3);
INSERT INTO Administrator (idUser) VALUES (4);
INSERT INTO Administrator (idUser) VALUES (5);
INSERT INTO Administrator (idUser) VALUES (6);

